-- ====================================================================
-- ATS SYSTEM - SUPABASE DATABASE SCHEMA INITIALIZATION
-- Run this script in the Supabase SQL Editor of your new Dev Project
-- ====================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'Recruiter',
    joining_date DATE DEFAULT CURRENT_DATE,
    relieving_date DATE,
    qualification TEXT,
    experience_years INT DEFAULT 0,
    experience_months INT DEFAULT 0,
    status TEXT DEFAULT 'Active',
    password_hash TEXT NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. MASTER TABLES
CREATE TABLE IF NOT EXISTS public.company_master (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.category_master (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sub_category_master (
    sub_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.category_master(category_id) ON DELETE CASCADE,
    sub_category_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.job_title_master (
    job_title_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title_name TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Active',
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. JOB MANAGEMENT
CREATE TABLE IF NOT EXISTS public.job_management (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_reference_no TEXT,
    job_title_id BIGINT REFERENCES public.job_title_master(job_title_id),
    company_id BIGINT REFERENCES public.company_master(company_id),
    category_id BIGINT REFERENCES public.category_master(category_id),
    sub_category_id BIGINT REFERENCES public.sub_category_master(sub_category_id),
    location TEXT,
    experience_min_year INT DEFAULT 0,
    experience_min_month INT DEFAULT 0,
    experience_max_year INT DEFAULT 0,
    experience_max_month INT DEFAULT 0,
    job_type TEXT DEFAULT 'Permanent',
    openings INT DEFAULT 1,
    pay_min NUMERIC,
    pay_max NUMERIC,
    currency TEXT DEFAULT 'INR',
    pay_unit TEXT DEFAULT 'Per Annum',
    skills_required TEXT,
    job_description TEXT,
    job_document_name TEXT,
    job_document_path TEXT,
    performa_invoice_no TEXT DEFAULT '',
    performa_invoice_status TEXT DEFAULT '',
    invoice_no TEXT DEFAULT '',
    invoice_status TEXT DEFAULT '',
    job_status TEXT DEFAULT 'Open',
    remark TEXT,
    created_by BIGINT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. JOB ASSIGNMENT
CREATE TABLE IF NOT EXISTS public.job_assignment (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.job_management(job_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. CANDIDATE MANAGEMENT
CREATE TABLE IF NOT EXISTS public.candidate_management (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_reference_no TEXT,
    job_id BIGINT REFERENCES public.job_management(job_id) ON DELETE SET NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    gender TEXT DEFAULT 'Not Specified',
    approx_dob DATE,
    email TEXT,
    mobile_no TEXT,
    alternate_mobile TEXT,
    current_location TEXT,
    experience_years INT DEFAULT 0,
    experience_months INT DEFAULT 0,
    current_company TEXT,
    current_designation TEXT,
    current_ctc NUMERIC,
    expected_ctc NUMERIC,
    notice_period TEXT,
    notice_negotiable TEXT DEFAULT 'No',
    skills TEXT,
    qualification TEXT,
    education_details TEXT,
    resume_name TEXT,
    resume_path TEXT,
    candidate_status TEXT DEFAULT 'Applied',
    current_stage TEXT DEFAULT 'Applied',
    remarks TEXT,
    created_by_user_id BIGINT,
    created_by_name TEXT,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_on TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. INTERVIEW MANAGEMENT
CREATE TABLE IF NOT EXISTS public.interview_management (
    interview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT REFERENCES public.candidate_management(candidate_id) ON DELETE CASCADE,
    job_id BIGINT REFERENCES public.job_management(job_id) ON DELETE CASCADE,
    interview_round TEXT DEFAULT 'L1',
    interview_date DATE,
    interview_time TIME,
    interviewer_name TEXT,
    interview_mode TEXT DEFAULT 'MS Teams',
    interview_status TEXT DEFAULT 'Scheduled',
    feedback TEXT,
    remarks TEXT,
    created_by_user_id BIGINT,
    created_by_name TEXT,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. OFFER MANAGEMENT
CREATE TABLE IF NOT EXISTS public.offer_management (
    offer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT REFERENCES public.candidate_management(candidate_id) ON DELETE CASCADE,
    job_id BIGINT REFERENCES public.job_management(job_id) ON DELETE CASCADE,
    offered_ctc NUMERIC,
    joining_date DATE,
    offer_status TEXT DEFAULT 'Offered',
    remarks TEXT,
    created_by_user_id BIGINT,
    created_by_name TEXT,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ====================================================================
-- SEED DATA (Default Admin User)
-- Default Login: serverdelhi1point@outlook.com
-- ====================================================================
INSERT INTO public.users (
    full_name, email, role, joining_date, qualification,
    experience_years, experience_months, status, password_hash
) VALUES (
    'System Admin',
    'serverdelhi1point@outlook.com',
    'Admin',
    CURRENT_DATE,
    'B Tech',
    5,
    0,
    'Active',
    '$2b$12$ULEqrYow4uPufCXJQA6UM.0ia4/aNx.B31.lwh2Rs3enpfeUAtE/C'
) ON CONFLICT (email) DO NOTHING;

-- ====================================================================
-- STORAGE BUCKETS & POLICIES (Run to enable file uploads)
-- ====================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('Resume', 'Resume', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('job_documents', 'job_documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Enable public access policies for storage
DO $$
BEGIN
    -- Resume policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert Resume') THEN
        CREATE POLICY "Allow public insert Resume" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'Resume');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select Resume') THEN
        CREATE POLICY "Allow public select Resume" ON storage.objects FOR SELECT TO public USING (bucket_id = 'Resume');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update Resume') THEN
        CREATE POLICY "Allow public update Resume" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'Resume');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete Resume') THEN
        CREATE POLICY "Allow public delete Resume" ON storage.objects FOR DELETE TO public USING (bucket_id = 'Resume');
    END IF;

    -- Job documents policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert job_documents') THEN
        CREATE POLICY "Allow public insert job_documents" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'job_documents');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select job_documents') THEN
        CREATE POLICY "Allow public select job_documents" ON storage.objects FOR SELECT TO public USING (bucket_id = 'job_documents');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update job_documents') THEN
        CREATE POLICY "Allow public update job_documents" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'job_documents');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete job_documents') THEN
        CREATE POLICY "Allow public delete job_documents" ON storage.objects FOR DELETE TO public USING (bucket_id = 'job_documents');
    END IF;
END $$;

-- ====================================================================
-- 8. LEGACY CANDIDATE ARCHIVE (511 Historical Candidate Profiles)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.legacy_candidates (
    legacy_candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_reference_no TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    gender TEXT DEFAULT 'Not Specified',
    approx_dob DATE,
    email TEXT,
    mobile_no TEXT,
    alternate_mobile TEXT,
    position_recommended TEXT,
    current_location TEXT,
    experience_years INT DEFAULT 0,
    experience_months INT DEFAULT 0,
    current_company TEXT,
    current_designation TEXT,
    current_ctc NUMERIC,
    expected_ctc NUMERIC,
    notice_period TEXT,
    notice_negotiable TEXT DEFAULT 'No',
    skills TEXT,
    qualification TEXT,
    education_details TEXT,
    resume_name TEXT,
    resume_path TEXT,
    created_on TIMESTAMP WITH TIME ZONE,
    imported_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_migrated_to_active BOOLEAN DEFAULT FALSE,
    migrated_candidate_id BIGINT REFERENCES public.candidate_management(candidate_id) ON DELETE SET NULL
);

-- Indexing for fast search & smart matching
CREATE INDEX IF NOT EXISTS idx_legacy_cand_ref ON public.legacy_candidates(candidate_reference_no);
CREATE INDEX IF NOT EXISTS idx_legacy_cand_email ON public.legacy_candidates(email);
CREATE INDEX IF NOT EXISTS idx_legacy_cand_mobile ON public.legacy_candidates(mobile_no);
CREATE INDEX IF NOT EXISTS idx_legacy_cand_loc ON public.legacy_candidates(current_location);

-- Enable RLS and public access
ALTER TABLE public.legacy_candidates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select legacy_candidates') THEN
        CREATE POLICY "Allow public select legacy_candidates" ON public.legacy_candidates FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert legacy_candidates') THEN
        CREATE POLICY "Allow public insert legacy_candidates" ON public.legacy_candidates FOR INSERT TO public WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update legacy_candidates') THEN
        CREATE POLICY "Allow public update legacy_candidates" ON public.legacy_candidates FOR UPDATE TO public USING (true);
    END IF;
END $$;

-- ====================================================================
-- 9. TALENT MAPPING TABLE (Company-wise Hierarchy & Market Intelligence)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.talent_mapping (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_type TEXT NOT NULL DEFAULT 'Chemicals',     -- Seeds, Chemicals, Fertilizer, Agro-Chemicals, Others
    company_name TEXT NOT NULL,                         -- e.g. 'UPL', 'Tata Chemicals'
    candidate_name TEXT NOT NULL,                      -- e.g. 'Candidate A'
    designation TEXT NOT NULL,                         -- e.g. 'Head of Production'
    location TEXT,                                     -- e.g. 'Mumbai', 'Vapi'
    experience TEXT,                                   -- e.g. '12 Years' or '12'
    current_ctc NUMERIC,                               -- e.g. 3000000
    expected_ctc NUMERIC,                              -- Optional / nullable
    contact_number TEXT,                               -- e.g. '9876543210'
    email_id TEXT,                                     -- e.g. 'candidate.a@example.com'
    comments TEXT,                                     -- Recruiter remarks / notes
    reports_to_id BIGINT REFERENCES public.talent_mapping(mapping_id) ON DELETE SET NULL, -- Hierarchy link: Reports To
    candidate_id BIGINT REFERENCES public.candidate_management(candidate_id) ON DELETE SET NULL, -- Optional ATS profile link
    created_by BIGINT,
    created_by_name TEXT,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_on TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexing for fast search & hierarchy queries
CREATE INDEX IF NOT EXISTS idx_talent_company ON public.talent_mapping(company_name);
CREATE INDEX IF NOT EXISTS idx_talent_company_type ON public.talent_mapping(company_type);
CREATE INDEX IF NOT EXISTS idx_talent_reports_to ON public.talent_mapping(reports_to_id);

-- Enable RLS and public policies
ALTER TABLE public.talent_mapping ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select talent_mapping') THEN
        CREATE POLICY "Allow public select talent_mapping" ON public.talent_mapping FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert talent_mapping') THEN
        CREATE POLICY "Allow public insert talent_mapping" ON public.talent_mapping FOR INSERT TO public WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public update talent_mapping') THEN
        CREATE POLICY "Allow public update talent_mapping" ON public.talent_mapping FOR UPDATE TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public delete talent_mapping') THEN
        CREATE POLICY "Allow public delete talent_mapping" ON public.talent_mapping FOR DELETE TO public USING (true);
    END IF;
END $$;

-- ====================================================================
-- 10. MIGRATION: DYNAMIC CANDIDATE AGE (approx_dob)
-- Run this in your Supabase SQL Editor to migrate existing databases
-- ====================================================================
ALTER TABLE public.candidate_management ADD COLUMN IF NOT EXISTS approx_dob DATE;
ALTER TABLE public.legacy_candidates ADD COLUMN IF NOT EXISTS approx_dob DATE;

-- Backfill approx_dob from existing approx_age and creation year
UPDATE public.candidate_management 
SET approx_dob = TO_DATE(
    (EXTRACT(YEAR FROM COALESCE(created_on, NOW())) - COALESCE(approx_age, 25))::TEXT || '-01-01', 
    'YYYY-MM-DD'
)
WHERE approx_dob IS NULL;

-- Optional: Drop legacy approx_age column once approx_dob is verified
ALTER TABLE public.candidate_management DROP COLUMN IF EXISTS approx_age;
ALTER TABLE public.legacy_candidates DROP COLUMN IF EXISTS approx_age;

-- Format legacy candidates reference numbers to 6-digit zero-padded format (LEG-000001 up to LEG-150000)
UPDATE public.legacy_candidates
SET candidate_reference_no = 'LEG-' || LPAD(
    COALESCE(
        NULLIF(REGEXP_REPLACE(candidate_reference_no, '\D', '', 'g'), ''),
        legacy_candidate_id::TEXT
    ),
    6,
    '0'
);





